### ISSUE TITLE
Could not recognize the .srt with just UTF-8 Unicode text

### ISSUE THREAD

**Issue by weisenhan** [kitone/subtitleeditor#58]
file 2.srt
2.srt: UTF-8 Unicode text
Is not recognized. [Screenshot](https://i.ibb.co/SchMrs9/Screenshot-at-2022-05-26-15-20-03.png) [Download](https://files.catbox.moe/3qk99z.srt)

file 1.srt
1.srt: UTF-8 Unicode (with BOM) text, with CRLF, LF line terminators
Is recognized

file little.srt
little.srt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
Recognized

file new.srt
new.srt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
2.srt rewritten as new.srt with another subtitle editor

Nothing major, prefer this program over others available.

**Comment by eltomito** [comment]
You got periods instead of commas in all the end timecodes. The very first subtitle starts:
```
1
00:01:16,902 --> 00:01:19.166
Lauren: FEAST YOUR EYES
ON A FAMILIAR SETTING --
```
See the period between 19 and 166? It has to be a comma. The same goes for all the other subtitles.

You can fix it with a regex replacement in a text editor. If you use Bluefish, you can do:
Search for:
`:([0-9]+)\.([0-9]+)`
Replace with:
`:\1,\2`

and you're good to go. Don't forget to select Match patter: Regular expression (pcre)
